### PR TITLE
Ability to add custom IPFS gateways to URLParams

### PR DESCRIPTION
**Pull request by kien-ngo**
@avneesh0612 @nachoiacovino 
We should be able to use the template with custom ipfs gateway as easy as this:

`https://nft-template.com/?customIpfsGateways=http://pinata-gw.cloud/ipfs`

Encouraging devs to roll their own gateways will benefit both parties since the end users do not have to share the same public gateway with million others and it'll put less stress on thirdweb's ipfs server

### CODE REVIEW

**Review by warengonzaga — COMMENTED** [review]
Good addition @kien-ngo let me add @eabdelmoneim here.

**Comment by warengonzaga** [comment]
Can we have the ability to define the custom IPFS to const file? @kien-ngo

**Comment by kien-ngo** [comment]
@warengonzaga Yes we do have it. I followed the same coding styles from the other contributors.
Basically you can set the value as consts like this:

```
import {
  biconomyApiIdConst,
  biconomyApiKeyConst,
  chainConst,
  customIpfsGateways, // <----- This one right here
  relayerUrlConst,
} from "./consts/parameters";
```

**Comment by warengonzaga** [comment]
Amazing work @kien-ngo thank you for your contribution, this will help our community!

**Comment by warengonzaga** [comment]
Adding @nachoiacovino and @MananTank here to take a look.

**Comment by saminacodes** [comment]
Can you take a look at the merge conflicts @kien-ngo

**Pull request closed without merging**
